
modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="delightandspice"
version="${file.jarVersion}"
displayName="Delight and Spice"
logoFile="logo.png"
credits="Milkfur, Pouffy"
authors="Pouffy, Milkfur"
description='''
A Farmer's Delight addon thought of by Milkfur and made a reality by countless YouTube tutorials!

Thanks to Milkfur for art assets
'''
[[dependencies.delightandspice]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.delightandspice]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.delightandspice]]
    modId="farmersdelight"
    mandatory=true
   versionRange="[1.1.2, 1.1.3)"
   ordering="NONE"
   side="BOTH"